apiVersion:  backstage.io/v1alpha1
kind: Component
metadata:
  name: NodejsApp
  description: This is a sample Nodejs app deployment
  annotations:
    backstage.io/managed-by-location: https://github.com/heraldofsolace/nodejs-app/blob/main/catalog-info.yaml
    github.com/project-slug: heraldofsolace/nodejs-app
    backstage.io/techdocs-ref: dir:.
  tags:
    - node
    - web
    - express

spec:
  type: service
  lifecycle: experimental
  owner: user:guest
  providesApis:
    - user-api
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: user-api
  description: The User Auth Service API
spec:
  type: openapi
  lifecycle: experimental
  owner: user:guest
  definition:
    $text: https://github.com/heraldofsolace/nodejs-app/blob/main/openapi.yaml
